### ISSUE TITLE
Create API POST endpoint for creating a new document

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v50-tier3-team-24#61]
Suggested HTTP route POST: /documents
- API route that create a new document to our DB

- [x] Validate the request body
- [x] Create appropriate slug from the title. Slugs can't have spaces as they form part of a URL. Suggest using kebab-case? The slug string should be properly formatted and sanitized as well.
- [ ] Slugs must be unique, check for duplicate slugs for the specific user (user functionality not available now, but consider this) and if so, append a dash and a sequential number ("-2") to the new slug.

- The new document should be inserted into the database.
- The API endpoint should probably return the path and some other data? to the front end

**Comment by kleenkanteen** [comment]
For creating it should be a post. I think you mean updating the relevant
data for an existing document?

Route name can just /documents, the data and alll be passed in the body
according to rest conventions. Conventions here:
***@***.***/rest-api-naming-conventions-and-best-practices-1c4e781eb6a5

**Comment by davideastmond** [comment]
Might be duplicated by #60
