### ISSUE TITLE
Create API GET route for retrieving a specific document

### ISSUE THREAD

**Issue by joekotvas** [chingu-voyages/v50-tier3-team-24#62]
- This GET route retrieves a specific document from the DB
create GET /document/:id
- What is the ID? the title? @joekotvas @Tandid @kleenkanteen

**Comment by kleenkanteen** [comment]
I would assume the unique identifier of the document inside the documents
table

**Comment by kleenkanteen** [comment]
Would be a auto-generated number then

**Comment by davideastmond** [comment]
Might be duplicated by #60
